spring:
    profiles:
        active: heroku
    application:
        name: Shop Demo
    mail:
        host: smtp.gmail.com
        username: nhantam181@gmail.com
        password: oydbafrodwpkkgzq
        port: 587
        properties.mail.smtp.starttls.enable: true
